Fix [Models endpoints monitoring, metrics] metrics selector freezes when changing pages
Taras-Hlukhovetskyi/ui pull request #105
Opened 2024-07-19 15:39 UTC by Taras-Hlukhovetskyi

https://iguazio.atlassian.net/browse/ML-7193

2024-07-22 13:12 UTC, mavdryk requested changes

2024-07-22 13:12 UTC, mavdryk commented on src/App.js
> +        <Suspense  fallback={<LoaderForSuspenseFallback />}>
delete redundant space

2024-07-22 13:12 UTC, mavdryk commented on src/common/Loader/LoaderForSuspenseFallback.js
> +
delete empty line

2024-07-22 14:40 UTC, Taras-Hlukhovetskyi commented on src/common/Loader/LoaderForSuspenseFallback.js
> +      document.getElementById('overlay_container').style.display = savedDisplayStyle
'unset' doesn't useful here

2024-07-23 14:00 UTC, mavdryk approved these changes

2024-07-23 15:29 UTC, closed without merging