Fix [Jobs, Workflows - cross project] Filter by 'Status' options should always be set
Taras-Hlukhovetskyi/ui pull request #106
Opened 2024-07-22 14:20 UTC by Taras-Hlukhovetskyi

https://iguazio.atlassian.net/browse/ML-7197

2024-07-26 11:01 UTC, mavdryk requested changes

2024-07-26 11:01 UTC, mavdryk commented on src/constants.js
> +export const STATUS_FILTER_NAME = 'state'
Use the existing `STATUS_FILTER` instead of the new constant

2024-07-26 11:01 UTC, mavdryk commented on src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoringFilters.js
> +import StatusFilter from '../../../common/StatusFilter/StatusFilter'
sort

2024-07-26 11:01 UTC, mavdryk commented on src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoringFilters.js
> +        <StatusFiler statusList={workflowsStatuses} name={STATUS_FILTER_NAME} />
Should be `StatusFilter`

2024-07-26 11:01 UTC, mavdryk commented on src/common/StatusFilter/StatusFilter.js
> +  statusList: PropTypes.array.isRequired
Should be arrayOf and not just general `array`. Add it to `types` file

2024-07-26 14:13 UTC, Taras-Hlukhovetskyi commented on src/constants.js
> +export const STATUS_FILTER_NAME = 'state'
-

2024-07-29 15:29 UTC, mavdryk approved these changes

2024-07-30 08:56 UTC, closed without merging