Fix [Model endpoints] switching to model/feature set overview is malfunctioning
Taras-Hlukhovetskyi/ui pull request #117
Opened 2024-08-22 08:38 UTC by Taras-Hlukhovetskyi

https://iguazio.atlassian.net/browse/ML-7582

2024-08-22 12:52 UTC, illia-prokopchuk requested changes

2024-08-22 12:52 UTC, illia-prokopchuk commented on src/components/ArtifactsActionBar/ArtifactsActionBar.js
> +  TAG_FILTER_ALL_ITEMS,
remove comma

2024-08-22 12:52 UTC, illia-prokopchuk commented on src/components/FeatureStore/FeatureSets/FeatureSets.js
> +    tagAbortControllerRef.current = new AbortController()
add an empty line

2024-08-22 12:52 UTC, illia-prokopchuk commented on src/components/FeatureStore/FeatureVectors/FeatureVectors.js
> +          const parsedResult = parseFeatureVectors(result)
add empty line

2024-08-22 12:52 UTC, illia-prokopchuk commented on src/components/FeatureStore/FeatureSets/FeatureSets.js
> +    return dispatch(
```suggestion
    return dispatch(
      getFilterTagOptions({
        fetchTags: fetchFeatureSetsTags,
        project: params.projectName,
        config: {
          signal: tagAbortControllerRef.current.signal
        }
      }))
```

2024-08-22 12:52 UTC, illia-prokopchuk commented on src/components/FeatureStore/FeatureSets/FeatureSets.js
> +    return dispatch(
please format

2024-08-22 12:52 UTC, illia-prokopchuk commented on src/components/FeatureStore/FeatureVectors/FeatureVectors.js
> +      getFilterTagOptions({ fetchTags: fetchFeatureVectorsTags, project: params.projectName, config: {
please format

2024-08-22 12:52 UTC, illia-prokopchuk commented on src/utils/tableRows.util.js
> +
remove empty line

2024-08-22 12:52 UTC, illia-prokopchuk commented on src/utils/tableRows.util.js
> + * @param {function} setExpandedRowsData - Function that set expanded date in state.
date => data

2024-08-29 10:41 UTC, mavdryk requested changes

2024-08-29 10:41 UTC, mavdryk commented on src/utils/tableRows.util.js
> + * @param {string} sortBy - Field by witch we will sort items
fix name and description

2024-08-29 10:41 UTC, mavdryk commented on src/utils/tableRows.util.js
> + * @param {Array} itemsList - List of table items.
extend Array type

2024-08-29 10:41 UTC, mavdryk commented on src/components/FunctionsPage/Functions.js
> +      const showUntagged = true
redundant variable

2024-08-29 10:41 UTC, mavdryk commented on src/utils/tableRows.util.js
> +      artifact => artifact?.db_key === name || artifact.name === name
this function isn't only for artifacts. Variable name isn't valid

2024-08-29 10:41 UTC, mavdryk commented on src/utils/tableRows.util.js
> +          content: (sortListBy ? sortListByDate(filteredItems, sortListBy, false) : filteredItems).map(artifact =>
this function isn't only for artifacts. Variable name isn't valid

2024-08-29 13:11 UTC, mavdryk approved these changes

2024-08-29 13:20 UTC, closed without merging